name: pokeapp
description: "Pokedex App"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.2.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  fuzzy_bolt: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
